swagger: "2.0"

info:
  title: "Rural Senses API"
  version: "1.0.0"

schemes:
  - "http"
  - "https"

securityDefinitions:
  token:
    type: "apiKey"
    scheme: "token"
    name: "Authorization"
    in: "header"

definitions:
  Error:
    type: "object"

  TokensPair:
    type: "object"
    properties:
      access:
        type: "string"
      refresh:
        type: "string"

  User:
    type: "object"
    properties:
      id:
        type: "string"
      role:
        type: "string"
      email:
        type: "string"
      profile:
        $ref: "#/definitions/Profile"

  Profile:
    type: "object"
    description: "one of these profiles according to role"
    properties:
      admin_profile:
        $ref: "#/definitions/AdminProfile"
      community_social_worker_profile:
        $ref: "#/definitions/CommunitySocialWorkerProfile"
      public_official_profile:
        $ref: "#/definitions/PublicOfficialProfile"

  AdminProfile:
    type: "object"
    properties:
      first_name:
        type: "string"
      last_name:
        type: "string"

  CommunitySocialWorkerProfile:
    type: "object"
    properties:
      first_name:
        type: "string"
      last_name:
        type: "string"

  PublicOfficialProfile:
    type: "object"
    properties:
      first_name:
        type: "string"
      last_name:
        type: "string"

  UsersPage:
    type: "object"
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/User"
      page:
        type: "integer"
      page_count:
        type: "integer"
