swagger: "2.0"

info:
  title: "Sound Oasis S600 Admin API"
  version: "1.0.0"

schemes:
  - "http"
  - "https"

securityDefinitions:
  token:
    type: "apiKey"
    scheme: "token"
    name: "Authorization"
    in: "header"

definitions:
  Error:
    type: "object"

  TokensPair:
    type: "object"
    properties:
      access:
        type: "string"
      refresh:
        type: "string"
